name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup dotNet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: NPM clear cache
      run: cd DotnetTemplate.Web && npm cache clean --force
    - name: NPM Install
      run: cd DotnetTemplate.Web && npm ci
    - name: NPM Build
      run: cd DotnetTemplate.Web && npm run build
    - name: NPM Test
      run: cd DotnetTemplate.Web && npm test